spring:
    application:
        name: imgxiv
    profiles:
        active: dev
    config:
        import: secret.yml
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false