spring:
    application:
        name: imgxiv
    profiles:
        active: dev
    config:
        import:
            - secret.yml
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false

springdoc:
    api-docs:
        path: /api/docs
    swagger-ui:
        path: /docs
        display-operation-id: true

feature:
    posts:
        query-caching:
            enable: true
        specification-caching:
            enable: true