spring:
    application:
        name: imgxiv
    profiles:
        active: dev
    config:
        import: secret.yml
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false

springdoc:
    api-docs:
        path: /api/docs
    swagger-ui:
        path: /docs
        display-operation-id: true

security:
    whitelist:
        - /api/docs/**
        - /docs/**
        - /v3/api-docs/**
        - /swagger-ui/**
        - /swagger-ui.html
        - /api/auth/**