spring:
    application:
        name: imgxiv
    profiles:
        active: dev
    config:
        import:
            - secret.yml
    jpa:
        show-sql: false
        properties:
            hibernate:
                format_sql: false

springdoc:
    api-docs:
        path: /api/docs
    swagger-ui:
        path: /docs
        display-operation-id: true
    use-method-annotations: true

interceptors:
    logging:
        enable: true
        path-patterns:
            - /api/**
        excluded-path-patterns:
            - /docs/**
            - /api/docs/**

feature:
    posts:
        query-caching:
            enable: true
        specification-caching:
            enable: true
    images:
        thumbnail:
            image-width: 200
            image-height: 200
            image-format: JPG
            content-type: image/jpeg